name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Get commit hash
        id: get-commit-hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
    - name: Build Docker image
      env:
        IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
        
      run: |
        docker build -t gaurdocker/hello-world:$IMAGE_TAG .

    - name: Push Docker image
      run: |
        docker push gaurdocker/hello-world:$IMAGE_TAG
